### ISSUE TITLE
Shift from .SLIM to .JADE for better Handlebars support

### ISSUE THREAD

**Issue by AndersSchmidtHansen** [AndersSchmidtHansen/Kaidan#1]
Note to self: Handlebars are not handled elegantly enough in .SLIM imho and I've discovered that good ol' Jade seems to do the work much better. Will make a version of Kaidan built with Jade and see if this should be the foundation instead.

**Comment by AndersSchmidtHansen** [comment]
Note to self: after some small tests it seems that Jade is the better choice, but I need to do some more research before I can make the move for sure.

**Comment by AndersSchmidtHansen** [comment]
NTS: For some reason it is impossible to disable a Jade warning that complains about missing whitespace before some text. It doesn't break the compiling, but it feels so wrong to write elegantly, but debug horribly. ;) Looking into different options.

**Comment by AndersSchmidtHansen** [comment]
NTS: Abandoning Jade, Emblem and HAML. The gulp plugins are simply not cutting it. Either there's strange, unnecessary warnings (Jade), a very strange build process (Emblem) and a mix of broken compiling (HAML). So, Kaidan will stick with Slim. :)

**Comment by simonh1000** [comment]
Did you try putting a `|` i.e. a pipe and a space ahead of any line with a {{...}}
Seems to be working at first glance

**Comment by AndersSchmidtHansen** [comment]
I'll take a look at it again soon :) Can't say for sure that the updated Gulp plugins might've fixed stuff since July last year, but back then it was broken.

**Comment by simonh1000** [comment]
No sweat. If you look at my fork, you will see an entire set of jade
templates that I think are working fine.
